# Generated by Django 2.1.3 on 2018-11-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBook', '0003_auto_20181119_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group',
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='apartment_number',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='city',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='country',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='house_number',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='state',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberaddress',
            name='street',
            field=models.CharField(default=None, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membergroup',
            name='member',
            field=models.ManyToManyField(to='ContactBook.Member'),
        ),
    ]
