# Generated by Django 2.1.3 on 2018-11-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContactBook', '0004_auto_20181120_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberaddress',
            name='city',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
